In [1]:
import pandas as pd


path = '../resources/symbol_windows/btcusdt-kline.csv'
df = pd.read_csv(path)
df

,timestamp,start_time,symbol,interval,first_trade_id,last_trade_id,open,close,high,low,volume,number_of_trades,is_closed,quote_asset_volume,taker_buy_asset_volume,taker_buy_quote_asset_volume,close_time
0,2023-04-06 20:56:00,NaN,btcusdt,NaN,NaN,NaN,27975.0,27975.0,27986.6,27972.5,294.104,2537,NaN,8.229491e+06,171.289,4.792977e+06,1.680815e+12
1,2023-04-06 20:57:00,NaN,btcusdt,NaN,NaN,NaN,27975.0,27960.8,27977.8,27958.8,275.259,2353,NaN,7.698763e+06,99.170,2.773652e+06,1.680815e+12
2,2023-04-06 20:58:00,NaN,btcusdt,NaN,NaN,NaN,27960.7,27971.6,27977.3,27952.6,315.054,2897,NaN,8.809524e+06,182.270,5.096760e+06,1.680815e+12
3,2023-04-06 20:59:00,NaN,btcusdt,NaN,NaN,NaN,27971.6,27965.1,27979.8,27965.0,234.820,2034,NaN,6.568455e+06,142.190,3.977423e+06,1.680815e+12
4,2023-04-06 21:00:00,NaN,btcusdt,NaN,NaN,NaN,27965.0,27948.8,27968.0,27948.7,456.475,3468,NaN,1.276267e+07,161.483,4.514916e+06,1.680815e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21521,2023-04-21 22:22:59.999,1.682116e+12,BTCUSDT,1m,257867568.0,257867672.0,27399.8,27310.0,27585.0,27310.0,58.154,105,True,1.591209e+06,25.561,7.006344e+05,NaN
21522,2023-04-21 22:23:59.999,1.682116e+12,BTCUSDT,1m,257867673.0,257867792.0,27343.3,27585.0,27585.0,27310.0,34.541,120,True,9.516269e+05,30.994,8.547409e+05,NaN
21523,2023-04-21 22:24:59.999,1.682116e+12,BTCUSDT,1m,257867793.0,257867902.0,27321.8,27326.4,27585.0,27320.0,42.295,110,True,1.159304e+06,14.084,3.884183e+05,NaN
21524,2023-04-21 22:25:59.999,1.682116e+12,BTCUSDT,1m,257867903.0,257868099.0,27331.0,27514.9,27589.4,27321.7,179.734,197,True,4.934826e+06,82.293,2.268937e+06,NaN
21525,2023-04-21 22:26:59.999,1.682116e+12,BTCUSDT,1m,257868100.0,257868356.0,27506.1,27394.9,27589.6,27330.0,122.168,257,True,3.357367e+06,76.564,2.110269e+06,NaN

In [2]:
groups = df.resample('W')
groups

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'